spring:
  application:
    name: "disponibilidad"

  datasource:
    url: jdbc:mysql://localhost:3306/disponibilidad_db
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
